







lng = []
lng.append(["Menu", "Menu", "قائمة"])
lng.append(["Home", "Accueil", "الرئيسية"])
lng.append(["Trash", "poubelle", "نفاية"])
lng.append(["Help", "Aide", "المساعدة"])
lng.append(["Setting", "Paramètres", "الإعدادات"])
lng.append(["Person Details", "Détails de personne", "تفاصيل الشخص"])
lng.append(["Name", "Nom", "اسم"])
lng.append(["Card id", "Carte d'identité", "بطاقة الهوية"])
lng.append(["last edit", "dernière modification", "التعديل الأخير"])
lng.append(["save", "enregistrer", "حفظ"])
lng.append(["Add debt", "Ajouter de la dette", "أضف دين"])
lng.append(["Description : ", "Description : ", ": وصف"])
lng.append(["Date : ", "Date : ", " : تاريخ"])
lng.append(["Amount : ", "montant : ", " : مبلغ"])
lng.append(["People", "Personnes", "الاشخاص"])
lng.append(["search", "chercher", "بحث"])
lng.append(["ID", "ID", "معرف"])
lng.append(["Total", "Total", "المجموع"])
lng.append(["add person", "ajouter un personne", "أضف شخص"])
lng.append(["remove person", "suprimer un personne", "ازل شخص"])
lng.append(["Debt details", "Détails de la dette", "تفاصيل الدين"])
lng.append(["Date", "Date", "التاريخ"])
lng.append(["remove debt", "supprimer la dette", "إزالة الدين"])
lng.append(["delete records", "supprimer les enregistrements", "حذف السجلات"])
lng.append(["Deletion time", "Heure de suppression", "وقت الحذف"])
lng.append(["Delete", "suprimer", "ازالة"])
lng.append(["recover", "récupérer", "استعادة"])
lng.append(["Delete all", "suprimer tout", "ازالةالكل"])
lng.append(["recover all", "récupérer tout", "استعادة الكل"])
lng.append(["all the deleted records\n will remain here for 30days\n  then will be deleted for ever", "tous les enregistrements supprimés\n resteront ici pendant 30 jours\n puis seront supprimés pour toujours", "جميع السجلات المحذوفة\n ستبقى هنا لمدة 30 يومًا\n ثم سيتم حذفها إلى الأبد"])
lng.append(["Close", "Fermer", "إغلاق"])
lng.append(["Style", "Style", "النمط"])
lng.append(["White", "Blanc", "أبيض"])
lng.append(["Black", "Noir", "أسود"])
lng.append(["Custom", "Personnalisé", "مخصص"])
lng.append(["Icons", "Icônes", "الأيقونات"])
lng.append(["White", "Blanc", "أبيض"])
lng.append(["Black", "Noir", "أسود"])
lng.append(["Custome", "Personnalisé", "مخصص"])
lng.append(["language", "Langue", "اللغة"])
lng.append(["English", "Anglais", "الإنجليزية"])
lng.append(["Français", "Français", "الفرنسية"])
lng.append(["Arabic", "Arabe", "العربية"])
lng.append(["currency", "Devise", "العملة"])
lng.append(["DH", "DH", "درهم"])
lng.append(["$", "$", "$"])
lng.append(["€", "€", "€"])
lng.append(["Create db copy", "Créer une copie de bd", "إنشاء نسخة من قاعدة البيانات"])
lng.append(["For more further help contact me on","Pour plus d'aide, contactez-moi au","لمزيد من المساعدة تواصل معي على"])
lng.append(["This app designed to handle very large amount of data smoothly ,if you encountered any problems please feel free contact us.", "Cette application est conçue pour gérer de très grandes quantités de données en douceur. Si vous rencontrez des problèmes, n'hésitez pas à nous contacter.","تم تصميم هذا التطبيق للتعامل مع كمية كبيرة جدًا من البيانات بسلاسة، إذا واجهت أي مشاكل فلا تتردد في الاتصال بنا."])
lng.append(["the database folder stored in", "le dossier de base de données stocké dans", "مجلد قاعدة البيانات مخزن في"])
lng.append((["create excel copy","créer une copie Excel","إنشاء نسخة إكسل"]))
lng.append(["Debt management", "Gestion de la dette", "إدارة الديون"])
lng.append(["Category table", "Tableau des catégories", "جدول الفئات"])
lng.append(["Category details", "Détails de la catégorie", "تفاصيل الفئة"])
lng.append(["Name", "Nom ", "اسم"])
lng.append(["Note", "Note", "ملاحظة"])
lng.append(["Add Category", "Ajouter une catégorie", "إضافة فئة"])
lng.append(["Remove Category", "Supprimer la catégorie", "إزالة الفئة"])
lng.append(["Excel", "Excel", "إكسل"])
lng.append(["Dashboard", "accueil", "عام"])
lng.append(["Categories", "Catégories", "فئات"])
lng.append(["Highest debt people", "Les personnes les plus endettées", "أعلى الناس ديونًا"])
lng.append(["oldest debt people ", "Les personnes les plus âgées endettées", "أقدم الناس ديونًا"])
lng.append(["Summary", "Résumé", "ملخص"])
lng.append(["Total amount of Debts :", "Montant total des dettes :", ": إجمالي مبلغ الديون"])
lng.append(["Total People : ", "Total de personnes : ", ": مجموع الأشخاص "])
lng.append(["Total Categories : ", "Total des catégories :", ": مجموع الفئات"])
lng.append(["Category", "catégorie", "الفئة"])
lng.append(["Plus +", "Plus +", "+ زائد"])
lng.append(["Minus -", "Moins -", "- ناقص"])
lng.append(["Phone number", "Numéro de téléphone", "رقم التليفون"])
lng.append(["Create a excel copy of :", "Créer une copie Excel de :", "إنشاء نسخة Excel من:"])
lng.append(["All data", "Toutes les données", "جميع البيانات"])
lng.append(["Data by categories", "Données par catégories", "البيانات حسب الفئات"])
lng.append(["Person by ID", "Personne par ID", "الشخص حسب المعرف"])
lng.append(["Category list", "Liste des catégories", "قائمة الفئات"])
lng.append(["Trash list", "Liste des déchets", "قائمة المهملات"])
lng.append(["NickName", "Surnom", "اللقب"])
lng.append(["Total amount of debt by Category", "Montant total de la dette par catégorie", "إجمالي مبلغ الديون حسب الفئة"])
lng.append(["€", "€", "€"])
lng.append(["€", "€", "€"])
lng.append(["€", "€", "€"])
lng.append(["€", "€", "€"])
lng.append(["€", "€", "€"])
lng.append(["€", "€", "€"])
lng.append(["€", "€", "€"])


lng2=[]
lng2.append(["Item Added","Article ajouté","تمت إضافة عنصر"])
lng2.append(["a person have been added ","une personne a été ajoutée ","لقد تم إضافة شخص"])
lng2.append(["confirmation","confirmation","تأكيد"])
lng2.append(["do you want to delete that Person","Voulez-vous supprimer ce personne","هل تريد حذف هذا الشخص؟"])
lng2.append(["Error","Erreur","خطأ"])
lng2.append(["please Select a Person","Veuillez sélectionner un persone","الرجاء اختيار الشخص"])
lng2.append(["success","succès","نجاح"])
lng2.append(["this person have been deleted,\n will stay in trash for 30 days before he will be deleted forever","cette personne a été supprimée,\n elle restera dans la corbeille pendant 30 jours avant d'être supprimée définitivement","تم حذف هذا الشخص,\n وسيبقى في سلة المهملات لمدة 30 يومًا قبل أن يتم حذفه إلى الأبد"])
lng2.append(["do you want to restore that person","veux-tu restaurer cette personne","هل تريد استعادة هذا الشخص"])
lng2.append(["do you want to empty the trash","tu veux vider la poubelle","هل تريد إفراغ سلة المهملات؟"])
lng2.append(["do you want to restore all deleted","voulez-vous restaurer tous les éléments supprimés","هل تريد استعادة جميع المحذوفات؟"])
lng2.append(["please insert a valid the informations","الرجاء إدخال المعلومات الصحيحة","veuillez insérer des informations valides"])
lng2.append(["please Select a debt row","Veuillez sélectionner une ligne de dette","الرجاء اختيار صف الدين"])
lng2.append(["do you want to delete this debt","Voulez-vous supprimer cette dette","هل تريد حذف هذا الدين؟"])
lng2.append(["success","succès","نجاح"])
lng2.append(["excel created successfully","Excel créé avec succès","تم إنشاء ملف Excel بنجاح"])
lng2.append(["Please insert the required information","Veuillez insérer les informations requises","الرجاء إدخال المعلومات المطلوبة"])
lng2.append(["Informations updated successfully","Informations mises à jour avec succès","تم تحديث المعلومات بنجاح"])
lng2.append(["do you want to delete this category?","Voulez-vous supprimer cette catégorie?","هل تريد حذف هذه الفئة؟"])
lng2.append(["this name is already used","ce nom est déjà utilisé","هذا الاسم مستخدم بالفعل"])
lng2.append(["select a category first","sélectionnez d'abord une catégorie","حدد الفئة أولا"])
lng2.append(["Copy created successfully","Une copy créé avec succès","تم إنشاء نسخة بنجاح"])








lng3=[]
lng3.append(["Add Category", "Ajouter une catégorie", "إضافة فئة"])
lng3.append(["Name", "Nom", "اسم"])
lng3.append(["Note", "Note", "ملاحظة"])
lng3.append(["Color", "Colour", "لون"])
lng3.append(["add person", "ajouter un personne", "أضف شخص"])
lng3.append(["Name", "Nom", "اسم"])
lng3.append(["NickName", "Surnom", "اللقب"])
lng3.append(["Card id", "Carte d'identité", "بطاقة الهوية"])
lng3.append(["Phone number", "Numéro de téléphone", "رقم التليفون"])
lng3.append(["Category", "catégorie", "الفئة"])
lng3.append(["Add debt", "Ajouter de la dette", "أضف دين"])
lng3.append(["Description : ", "Description : ", ": وصف"])
lng3.append(["Date : ", "Date : ", " : تاريخ"])
lng3.append(["Amount : ", "montant : ", " : مبلغ"])
